flink:
  deploy:
    yarnname: StreamingJob            # Set a custom name for the application on YARN
    main:                             # main class
    mainParams:                       # main param
    detached:                         # -d   (If present, runs the job in detached mode)
    jobmanager:                       # -m   (Address of the JobManager (master) to which to connect. Use this flag to connect to a different JobManager than the one specified in the configuration.)
    shutdownOnAttachedExit:           # -sae (If the job is submitted in attached mode, perform a best-effort cluster shutdown when the CLI is terminated abruptly, e.g., in response to a user interrupt, such as typing Ctrl + C.)
    yarnapplicationType:              # -yat (Set a custom application type for the application on YARN)
    yarndetached:                     # -yd  (If present, runs the job in detached mode (deprecated; use non-YARN specific option instead))
    yarnapplicationId:                # -yid (Attach to running YARN session)
    yarnjobManagerMemory:             # -yjm (Memory for JobManager Container with optional unit (default: MB))
    yarncontainer:                    # -yn  (Number of YARN container to allocate (=Number of Task Managers)
    yarnnodeLabel:                    # -ynl (Specify YARN node label for the YARN application)
    yarnqueue:                        # -yqu (Specify YARN queue)
    yarnslots:                        # -ys  (Number of slots per TaskManager)
    yarntaskManagerMemory:            # -ytm

