# Using the container-based infrastructure
sudo: false

language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

install:
  /bin/true

script:
  ./test.sh
