mysql:
  driverClassName: com.mysql.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost:3306/test
  username: root
  password: 123322242
  batch.size: 100

# hbase
hbase:
  zookeeper.quorum: test-hadoop-1,test-hadoop-2,test-hadoop-6
  zookeeper.property.clientPort: 2181

#clickhouse
clickhouse.sink:
  driverClassName:
  jdbcUrl: http://192.168.0.100:8123
  username: default
  password: 123322242
  async:
    bufferSize: 1000
    numWriters: 3
    queueCapacity: 1000
    timeout: 1000
    failover:
      retries: 10 #一条记录当插入失败时重试的最大次数
      storage: mysql #kafka,hbase,hdfs
      mysql: # 保存类型为MySQL,将失败的数据保存到MySQL
        jdbcUrl: jdbc:mysql://localhost:3306/test
        username: root
        password: 123322242
      #storage: hbase
      hbase:
        zookeeper.quorum: test-hadoop-1,test-hadoop-2,test-hadoop-6
        zookeeper.property.clientPort: 2181
      hdfs:
        path: hdfs://hadoop:9000/flink


