mysql:
  driverClassName: com.mysql.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost:3306/test
  username: root
  password: 123322242
  batch.size: 100

# hbase
hbase:
  zookeeper.quorum: test-hadoop-1,test-hadoop-2,test-hadoop-6
  zookeeper.property.clientPort: 2181

clickhouse.sink:
  driverClassName:
  host: 192.168.0.100
  username: default
  password: 123322242
  table: default
  async:
    buffer-size: 10240
    num-writers: 3
    queue-capacity: 1000
    timeout: 1000
    retries: 10
    failed-path: /tmp/failed_records