mysql:
  driverClassName: com.mysql.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost:3306/test
  username: root
  password: 123322242

# hbase
hbase:
  zookeeper.quorum: test-hadoop-1,test-hadoop-2,test-hadoop-6
  zookeeper.property.clientPort: 2181

clickhouse:
  driverClassName:
  jdbcUrl: jdbc:clickhouse://localhost:8123
  username: default
  password:
