header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'

  comment: on-failure

# If you want to check dependencies' license compatibility, uncomment the following section
# dependency:
   files:
     - pom.xml           # If this is a maven project.
     - package.json      # If this is a npm project.
