# SonarCloud automatic analysis reads this file (not sonar-project.properties).
sonar.cpd.exclusions=**/streampark-flink-shims/**,**/streampark-spark-shims/**,**/streampark-flink-shims-base/**,**/streampark-flink-shims-base-v2/**,**/streampark-flink-connector/**,**/streampark-flink-kubernetes/**,**/streampark-flink-packer/**
