# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SonarCloud automatic analysis reads this file (not sonar-project.properties).
sonar.cpd.exclusions=**/streampark-flink-shims/**,**/streampark-spark-shims/**,**/streampark-flink-shims-base/**,**/streampark-flink-shims-base-v2/**,**/streampark-flink-connector/**,**/streampark-flink-kubernetes/**,**/streampark-flink-packer/**

sonar.issue.ignore.multicriteria=s2083safepath,s100shims,s1948connector,s6355shims,s1123deprecated,s1133deprecated,s6355shimsall,s8786sqlconvert,s112client,s1186silent
sonar.issue.ignore.multicriteria.s2083safepath.ruleKey=javasecurity:S2083
sonar.issue.ignore.multicriteria.s2083safepath.resourceKey=**/SafePathUtils.java
sonar.issue.ignore.multicriteria.s100shims.ruleKey=java:S100
sonar.issue.ignore.multicriteria.s100shims.resourceKey=**/streampark-flink-shims*/**
sonar.issue.ignore.multicriteria.s1948connector.ruleKey=java:S1948
sonar.issue.ignore.multicriteria.s1948connector.resourceKey=**/streampark-flink-connector/**
sonar.issue.ignore.multicriteria.s6355shims.ruleKey=java:S6355
sonar.issue.ignore.multicriteria.s6355shims.resourceKey=**/FlinkStreamTableTrait*.java
sonar.issue.ignore.multicriteria.s1123deprecated.ruleKey=java:S1123
sonar.issue.ignore.multicriteria.s1123deprecated.resourceKey=**/FlinkStreamTableTrait*.java
sonar.issue.ignore.multicriteria.s1133deprecated.ruleKey=java:S1133
sonar.issue.ignore.multicriteria.s1133deprecated.resourceKey=**/FlinkStreamTableTrait*.java
sonar.issue.ignore.multicriteria.s6355shimsall.ruleKey=java:S6355
sonar.issue.ignore.multicriteria.s6355shimsall.resourceKey=**/streampark-flink-shims*/**
sonar.issue.ignore.multicriteria.s8786sqlconvert.ruleKey=java:S8786
sonar.issue.ignore.multicriteria.s8786sqlconvert.resourceKey=**/SqlConvertUtils.java
sonar.issue.ignore.multicriteria.s112client.ruleKey=java:S112
sonar.issue.ignore.multicriteria.s112client.resourceKey=**/streampark-*-client*/**
sonar.issue.ignore.multicriteria.s1186silent.ruleKey=java:S1186
sonar.issue.ignore.multicriteria.s1186silent.resourceKey=**/Silent*.java
