spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:streamx;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=true;INIT=runscript from 'classpath:db/schema-h2.sql'\;runscript from 'classpath:db/data-h2.sql'
    username: sa
    password: sa
