/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { Component } from 'vue'
import {
  AddCircleOutline,
  AddOutline,
  AlertCircleOutline,
  AppsOutline,
  ArchiveOutline,
  ArrowBackOutline,
  ArrowForwardOutline,
  ArrowUpOutline,
  BookOutline,
  BodyOutline,
  CameraOutline,
  ChatbubbleEllipsesOutline,
  ChatbubbleOutline,
  CheckmarkOutline,
  ChevronBackOutline,
  ChevronDownCircleOutline,
  ChevronForwardOutline,
  CloseOutline,
  CloudOutline,
  CloudUploadOutline,
  CodeSlashOutline,
  ContractOutline,
  CopyOutline,
  CreateOutline,
  CubeOutline,
  DesktopOutline,
  DocumentTextOutline,
  EllipsisHorizontalOutline,
  ExpandOutline,
  EyeOffOutline,
  EyeOutline,
  FlashOutline,
  FolderOpenOutline,
  GitCompareOutline,
  GitNetworkOutline,
  HappyOutline,
  HelpCircleOutline,
  HomeOutline,
  InformationCircleOutline,
  KeyOutline,
  LanguageOutline,
  LinkOutline,
  LockClosedOutline,
  LockOpenOutline,
  LogInOutline,
  LogOutOutline,
  LogoGithub,
  MailOutline,
  MenuOutline,
  MoonOutline,
  NotificationsOutline,
  PauseCircleOutline,
  PeopleOutline,
  PersonAddOutline,
  PersonOutline,
  PlayCircleOutline,
  RefreshOutline,
  ReorderThreeOutline,
  ReorderTwoOutline,
  ResizeOutline,
  RibbonOutline,
  SearchOutline,
  ServerOutline,
  SettingsOutline,
  ShareSocialOutline,
  SpeedometerOutline,
  StarOutline,
  SunnyOutline,
  SwapHorizontalOutline,
  SyncOutline,
  TimeOutline,
  TrashOutline,
  TrophyOutline,
  UmbrellaOutline,
  WarningOutline,
} from '@vicons/ionicons5'

/** Explicit @vicons/ionicons5 registry for tree-shaking. */
export const ION_ICON_REGISTRY: Record<string, Component> = {
  AddCircleOutline,
  AddOutline,
  AlertCircleOutline,
  AppsOutline,
  ArchiveOutline,
  ArrowBackOutline,
  ArrowForwardOutline,
  ArrowUpOutline,
  BookOutline,
  BodyOutline,
  CameraOutline,
  ChatbubbleEllipsesOutline,
  ChatbubbleOutline,
  CheckmarkOutline,
  ChevronBackOutline,
  ChevronDownCircleOutline,
  ChevronForwardOutline,
  CloseOutline,
  CloudOutline,
  CloudUploadOutline,
  CodeSlashOutline,
  ContractOutline,
  CopyOutline,
  CreateOutline,
  CubeOutline,
  DesktopOutline,
  DocumentTextOutline,
  EllipsisHorizontalOutline,
  ExpandOutline,
  EyeOffOutline,
  EyeOutline,
  FlashOutline,
  FolderOpenOutline,
  GitCompareOutline,
  GitNetworkOutline,
  HappyOutline,
  HelpCircleOutline,
  HomeOutline,
  InformationCircleOutline,
  KeyOutline,
  LanguageOutline,
  LinkOutline,
  LockClosedOutline,
  LockOpenOutline,
  LogInOutline,
  LogOutOutline,
  LogoGithub,
  MailOutline,
  MenuOutline,
  MoonOutline,
  NotificationsOutline,
  PauseCircleOutline,
  PeopleOutline,
  PersonAddOutline,
  PersonOutline,
  PlayCircleOutline,
  RefreshOutline,
  ReorderThreeOutline,
  ReorderTwoOutline,
  ResizeOutline,
  RibbonOutline,
  SearchOutline,
  ServerOutline,
  SettingsOutline,
  ShareSocialOutline,
  SpeedometerOutline,
  StarOutline,
  SunnyOutline,
  SwapHorizontalOutline,
  SyncOutline,
  TimeOutline,
  TrashOutline,
  TrophyOutline,
  UmbrellaOutline,
  WarningOutline,
}

export function ionIdToComponentName(ionId: string): string {
  const name = ionId.replace(/^ion:/, '')
  return name
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}
