name: Maven Package Test

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**.md'
      - 'deploy/**'
      - 'script/**'
      - 'streampark-console/streampark-console-webapp/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'deploy/**'
      - 'script/**'
      - 'streampark-console/streampark-console-webapp/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package -T 4 -DskipTests
      - name: Test with Maven
        run: mvn -B test -pl '!streampark-plugin/streampark-jvm-profiler,!streampark-console/streampark-console-service' -am
#      - name: Setup Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: '1.16'
#      - name: Check Dependencies Licenses
#        run: |
#          go install github.com/apache/skywalking-eyes/cmd/license-eye@47febf5
#          license-eye dependency resolve --summary ./dist-material/release-docs/LICENSE.tpl
