#!/usr/bin/env bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT_DIR="${ROOT_DIR}/tools/openapi/generated"
JSON_FILE="${OUTPUT_DIR}/api-contracts.json"
TS_FILE="${OUTPUT_DIR}/api-types.ts"

mkdir -p "${OUTPUT_DIR}"

echo "Running API contract export tests..."
(
  cd "${ROOT_DIR}"
  ./mvnw -q -pl streampark-console/streampark-console-service \
    -Dtest=ApiTypeScriptGeneratorTest \
    -Dspotless.check.skip=true \
    -Drat.skip=true \
    -Dcheckstyle.skip=true \
    test
)

cat > "${TS_FILE}" <<'EOF'
// Placeholder generated by export-api-schemas.sh.
// Run the console and call POST /openapi/contracts/typescript for a live export,
// or extend ApiSchemaExportMain to write files during build.
export {};
EOF

echo "API schema tooling verified. Output directory: ${OUTPUT_DIR}"
echo "Use POST /openapi/contracts and POST /openapi/contracts/typescript at runtime for full export."
