/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by auto-proxy
// biome-ignore lint: disable
export {}

type serviceName = never

declare global {
  const __URL_MAP__: {
    [K in serviceName]: {
      path: string
      rawPath: string
    }
  }
}
