/* Generated By:JavaCC: Do not edit this line. FlinkSqlParserImplConstants.java */
package org.apache.flink.sql.parser.impl;

public interface FlinkSqlParserImplConstants {

  int EOF = 0;
  int A = 1;
  int ABS = 2;
  int ABSENT = 3;
  int ABSOLUTE = 4;
  int ACTION = 5;
  int ADA = 6;
  int ADD = 7;
  int ADMIN = 8;
  int AFTER = 9;
  int ALL = 10;
  int ALLOCATE = 11;
  int ALLOW = 12;
  int ALTER = 13;
  int ALWAYS = 14;
  int AND = 15;
  int ANY = 16;
  int APPLY = 17;
  int ARE = 18;
  int ARRAY = 19;
  int ARRAY_MAX_CARDINALITY = 20;
  int AS = 21;
  int ASC = 22;
  int ASENSITIVE = 23;
  int ASSERTION = 24;
  int ASSIGNMENT = 25;
  int ASYMMETRIC = 26;
  int AT = 27;
  int ATOMIC = 28;
  int ATTRIBUTE = 29;
  int ATTRIBUTES = 30;
  int AUTHORIZATION = 31;
  int AVG = 32;
  int BEFORE = 33;
  int BEGIN = 34;
  int BEGIN_FRAME = 35;
  int BEGIN_PARTITION = 36;
  int BERNOULLI = 37;
  int BETWEEN = 38;
  int BIGINT = 39;
  int BINARY = 40;
  int BIT = 41;
  int BLOB = 42;
  int BOOLEAN = 43;
  int BOTH = 44;
  int BREADTH = 45;
  int BY = 46;
  int C = 47;
  int CALL = 48;
  int CALLED = 49;
  int CARDINALITY = 50;
  int CASCADE = 51;
  int CASCADED = 52;
  int CASE = 53;
  int CAST = 54;
  int CATALOG = 55;
  int CATALOG_NAME = 56;
  int CEIL = 57;
  int CEILING = 58;
  int CENTURY = 59;
  int CHAIN = 60;
  int CHAR = 61;
  int CHAR_LENGTH = 62;
  int CHARACTER = 63;
  int CHARACTER_LENGTH = 64;
  int CHARACTER_SET_CATALOG = 65;
  int CHARACTER_SET_NAME = 66;
  int CHARACTER_SET_SCHEMA = 67;
  int CHARACTERISTICS = 68;
  int CHARACTERS = 69;
  int CHECK = 70;
  int CLASSIFIER = 71;
  int CLASS_ORIGIN = 72;
  int CLOB = 73;
  int CLOSE = 74;
  int COALESCE = 75;
  int COBOL = 76;
  int COLLATE = 77;
  int COLLATION = 78;
  int COLLATION_CATALOG = 79;
  int COLLATION_NAME = 80;
  int COLLATION_SCHEMA = 81;
  int COLLECT = 82;
  int COLUMN = 83;
  int COLUMN_NAME = 84;
  int COMMAND_FUNCTION = 85;
  int COMMAND_FUNCTION_CODE = 86;
  int COMMIT = 87;
  int COMMITTED = 88;
  int CONDITION = 89;
  int CONDITIONAL = 90;
  int CONDITION_NUMBER = 91;
  int CONNECT = 92;
  int CONNECTION = 93;
  int CONNECTION_NAME = 94;
  int CONSTRAINT = 95;
  int CONSTRAINT_CATALOG = 96;
  int CONSTRAINT_NAME = 97;
  int CONSTRAINT_SCHEMA = 98;
  int CONSTRAINTS = 99;
  int CONSTRUCTOR = 100;
  int CONTAINS = 101;
  int CONTINUE = 102;
  int CONVERT = 103;
  int CORR = 104;
  int CORRESPONDING = 105;
  int COUNT = 106;
  int COVAR_POP = 107;
  int COVAR_SAMP = 108;
  int CREATE = 109;
  int CROSS = 110;
  int CUBE = 111;
  int CUME_DIST = 112;
  int CURRENT = 113;
  int CURRENT_CATALOG = 114;
  int CURRENT_DATE = 115;
  int CURRENT_DEFAULT_TRANSFORM_GROUP = 116;
  int CURRENT_PATH = 117;
  int CURRENT_ROLE = 118;
  int CURRENT_ROW = 119;
  int CURRENT_SCHEMA = 120;
  int CURRENT_TIME = 121;
  int CURRENT_TIMESTAMP = 122;
  int CURRENT_TRANSFORM_GROUP_FOR_TYPE = 123;
  int CURRENT_USER = 124;
  int CURSOR = 125;
  int CURSOR_NAME = 126;
  int CYCLE = 127;
  int DATA = 128;
  int DATABASE = 129;
  int DATE = 130;
  int DATETIME_INTERVAL_CODE = 131;
  int DATETIME_INTERVAL_PRECISION = 132;
  int DAY = 133;
  int DAYS = 134;
  int DEALLOCATE = 135;
  int DEC = 136;
  int DECADE = 137;
  int DECIMAL = 138;
  int DECLARE = 139;
  int DEFAULT_ = 140;
  int DEFAULTS = 141;
  int DEFERRABLE = 142;
  int DEFERRED = 143;
  int DEFINE = 144;
  int DEFINED = 145;
  int DEFINER = 146;
  int DEGREE = 147;
  int DELETE = 148;
  int DENSE_RANK = 149;
  int DEPTH = 150;
  int DEREF = 151;
  int DERIVED = 152;
  int DESC = 153;
  int DESCRIBE = 154;
  int DESCRIPTION = 155;
  int DESCRIPTOR = 156;
  int DETERMINISTIC = 157;
  int DIAGNOSTICS = 158;
  int DISALLOW = 159;
  int DISCONNECT = 160;
  int DISPATCH = 161;
  int DISTINCT = 162;
  int DOMAIN = 163;
  int DOUBLE = 164;
  int DOW = 165;
  int DOY = 166;
  int DROP = 167;
  int DYNAMIC = 168;
  int DYNAMIC_FUNCTION = 169;
  int DYNAMIC_FUNCTION_CODE = 170;
  int EACH = 171;
  int ELEMENT = 172;
  int ELSE = 173;
  int EMPTY = 174;
  int ENCODING = 175;
  int END = 176;
  int END_EXEC = 177;
  int END_FRAME = 178;
  int END_PARTITION = 179;
  int EPOCH = 180;
  int EQUALS = 181;
  int ERROR = 182;
  int ESCAPE = 183;
  int EVERY = 184;
  int EXCEPT = 185;
  int EXCEPTION = 186;
  int EXCLUDE = 187;
  int EXCLUDING = 188;
  int EXEC = 189;
  int EXECUTE = 190;
  int EXISTS = 191;
  int EXP = 192;
  int EXPLAIN = 193;
  int EXTEND = 194;
  int EXTERNAL = 195;
  int EXTRACT = 196;
  int FALSE = 197;
  int FETCH = 198;
  int FILTER = 199;
  int FINAL = 200;
  int FIRST = 201;
  int FIRST_VALUE = 202;
  int FLOAT = 203;
  int FLOOR = 204;
  int FOLLOWING = 205;
  int FOR = 206;
  int FORMAT = 207;
  int FOREIGN = 208;
  int FORTRAN = 209;
  int FOUND = 210;
  int FRAC_SECOND = 211;
  int FRAME_ROW = 212;
  int FREE = 213;
  int FROM = 214;
  int FULL = 215;
  int FUNCTION = 216;
  int FUSION = 217;
  int G = 218;
  int GENERAL = 219;
  int GENERATED = 220;
  int GEOMETRY = 221;
  int GET = 222;
  int GLOBAL = 223;
  int GO = 224;
  int GOTO = 225;
  int GRANT = 226;
  int GRANTED = 227;
  int GROUP = 228;
  int GROUPING = 229;
  int GROUPS = 230;
  int HAVING = 231;
  int HIERARCHY = 232;
  int HOLD = 233;
  int HOP = 234;
  int HOUR = 235;
  int HOURS = 236;
  int IDENTITY = 237;
  int IGNORE = 238;
  int IMMEDIATE = 239;
  int IMMEDIATELY = 240;
  int IMPLEMENTATION = 241;
  int IMPORT = 242;
  int IN = 243;
  int INCLUDING = 244;
  int INCREMENT = 245;
  int INDICATOR = 246;
  int INITIAL = 247;
  int INITIALLY = 248;
  int INNER = 249;
  int INOUT = 250;
  int INPUT = 251;
  int INSENSITIVE = 252;
  int INSERT = 253;
  int INSTANCE = 254;
  int INSTANTIABLE = 255;
  int INT = 256;
  int INTEGER = 257;
  int INTERSECT = 258;
  int INTERSECTION = 259;
  int INTERVAL = 260;
  int INTO = 261;
  int INVOKER = 262;
  int IS = 263;
  int ISODOW = 264;
  int ISOYEAR = 265;
  int ISOLATION = 266;
  int JAVA = 267;
  int JOIN = 268;
  int JSON = 269;
  int JSON_ARRAY = 270;
  int JSON_ARRAYAGG = 271;
  int JSON_EXISTS = 272;
  int JSON_OBJECT = 273;
  int JSON_OBJECTAGG = 274;
  int JSON_QUERY = 275;
  int JSON_VALUE = 276;
  int K = 277;
  int KEY = 278;
  int KEY_MEMBER = 279;
  int KEY_TYPE = 280;
  int LABEL = 281;
  int LAG = 282;
  int LANGUAGE = 283;
  int LARGE = 284;
  int LAST = 285;
  int LAST_VALUE = 286;
  int LATERAL = 287;
  int LEAD = 288;
  int LEADING = 289;
  int LEFT = 290;
  int LENGTH = 291;
  int LEVEL = 292;
  int LIBRARY = 293;
  int LIKE = 294;
  int LIKE_REGEX = 295;
  int LIMIT = 296;
  int LN = 297;
  int LOCAL = 298;
  int LOCALTIME = 299;
  int LOCALTIMESTAMP = 300;
  int LOCATOR = 301;
  int LOWER = 302;
  int M = 303;
  int MAP = 304;
  int MATCH = 305;
  int MATCHED = 306;
  int MATCHES = 307;
  int MATCH_NUMBER = 308;
  int MATCH_RECOGNIZE = 309;
  int MAX = 310;
  int MAXVALUE = 311;
  int MEASURES = 312;
  int MEMBER = 313;
  int MERGE = 314;
  int MESSAGE_LENGTH = 315;
  int MESSAGE_OCTET_LENGTH = 316;
  int MESSAGE_TEXT = 317;
  int METHOD = 318;
  int MICROSECOND = 319;
  int MILLISECOND = 320;
  int MILLENNIUM = 321;
  int MIN = 322;
  int MINUTE = 323;
  int MINUTES = 324;
  int MINVALUE = 325;
  int MOD = 326;
  int MODIFIES = 327;
  int MODULE = 328;
  int MONTH = 329;
  int MONTHS = 330;
  int MORE_ = 331;
  int MULTISET = 332;
  int MUMPS = 333;
  int NAME = 334;
  int NAMES = 335;
  int NANOSECOND = 336;
  int NATIONAL = 337;
  int NATURAL = 338;
  int NCHAR = 339;
  int NCLOB = 340;
  int NESTING = 341;
  int NEW = 342;
  int NEXT = 343;
  int NO = 344;
  int NONE = 345;
  int NORMALIZE = 346;
  int NORMALIZED = 347;
  int NOT = 348;
  int NTH_VALUE = 349;
  int NTILE = 350;
  int NULL = 351;
  int NULLABLE = 352;
  int NULLIF = 353;
  int NULLS = 354;
  int NUMBER = 355;
  int NUMERIC = 356;
  int OBJECT = 357;
  int OCCURRENCES_REGEX = 358;
  int OCTET_LENGTH = 359;
  int OCTETS = 360;
  int OF = 361;
  int OFFSET = 362;
  int OLD = 363;
  int OMIT = 364;
  int ON = 365;
  int ONE = 366;
  int ONLY = 367;
  int OPEN = 368;
  int OPTION = 369;
  int OPTIONS = 370;
  int OR = 371;
  int ORDER = 372;
  int ORDERING = 373;
  int ORDINALITY = 374;
  int OTHERS = 375;
  int OUT = 376;
  int OUTER = 377;
  int OUTPUT = 378;
  int OVER = 379;
  int OVERLAPS = 380;
  int OVERLAY = 381;
  int OVERRIDING = 382;
  int PAD = 383;
  int PARAMETER = 384;
  int PARAMETER_MODE = 385;
  int PARAMETER_NAME = 386;
  int PARAMETER_ORDINAL_POSITION = 387;
  int PARAMETER_SPECIFIC_CATALOG = 388;
  int PARAMETER_SPECIFIC_NAME = 389;
  int PARAMETER_SPECIFIC_SCHEMA = 390;
  int PARTIAL = 391;
  int PARTITION = 392;
  int PASCAL = 393;
  int PASSING = 394;
  int PASSTHROUGH = 395;
  int PAST = 396;
  int PATH = 397;
  int PATTERN = 398;
  int PER = 399;
  int PERCENT = 400;
  int PERCENTILE_CONT = 401;
  int PERCENTILE_DISC = 402;
  int PERCENT_RANK = 403;
  int PERIOD = 404;
  int PERMUTE = 405;
  int PIVOT = 406;
  int PLACING = 407;
  int PLAN = 408;
  int PLI = 409;
  int PORTION = 410;
  int POSITION = 411;
  int POSITION_REGEX = 412;
  int POWER = 413;
  int PRECEDES = 414;
  int PRECEDING = 415;
  int PRECISION = 416;
  int PREPARE = 417;
  int PRESERVE = 418;
  int PREV = 419;
  int PRIMARY = 420;
  int PRIOR = 421;
  int PRIVILEGES = 422;
  int PROCEDURE = 423;
  int PUBLIC = 424;
  int QUARTER = 425;
  int RANGE = 426;
  int RANK = 427;
  int READ = 428;
  int READS = 429;
  int REAL = 430;
  int RECURSIVE = 431;
  int REF = 432;
  int REFERENCES = 433;
  int REFERENCING = 434;
  int REGR_AVGX = 435;
  int REGR_AVGY = 436;
  int REGR_COUNT = 437;
  int REGR_INTERCEPT = 438;
  int REGR_R2 = 439;
  int REGR_SLOPE = 440;
  int REGR_SXX = 441;
  int REGR_SXY = 442;
  int REGR_SYY = 443;
  int RELATIVE = 444;
  int RELEASE = 445;
  int REPEATABLE = 446;
  int REPLACE = 447;
  int RESET = 448;
  int RESPECT = 449;
  int RESTART = 450;
  int RESTRICT = 451;
  int RESULT = 452;
  int RETURN = 453;
  int RETURNED_CARDINALITY = 454;
  int RETURNED_LENGTH = 455;
  int RETURNED_OCTET_LENGTH = 456;
  int RETURNED_SQLSTATE = 457;
  int RETURNING = 458;
  int RETURNS = 459;
  int REVOKE = 460;
  int RIGHT = 461;
  int ROLE = 462;
  int ROLLBACK = 463;
  int ROLLUP = 464;
  int ROUTINE = 465;
  int ROUTINE_CATALOG = 466;
  int ROUTINE_NAME = 467;
  int ROUTINE_SCHEMA = 468;
  int ROW = 469;
  int ROW_COUNT = 470;
  int ROW_NUMBER = 471;
  int ROWS = 472;
  int RUNNING = 473;
  int SAVEPOINT = 474;
  int SCALAR = 475;
  int SCALE = 476;
  int SCHEMA = 477;
  int SCHEMA_NAME = 478;
  int SCOPE = 479;
  int SCOPE_CATALOGS = 480;
  int SCOPE_NAME = 481;
  int SCOPE_SCHEMA = 482;
  int SCROLL = 483;
  int SEARCH = 484;
  int SECOND = 485;
  int SECONDS = 486;
  int SECTION = 487;
  int SECURITY = 488;
  int SEEK = 489;
  int SELECT = 490;
  int SELF = 491;
  int SENSITIVE = 492;
  int SEQUENCE = 493;
  int SERIALIZABLE = 494;
  int SERVER = 495;
  int SERVER_NAME = 496;
  int SESSION = 497;
  int SESSION_USER = 498;
  int SET = 499;
  int SETS = 500;
  int SET_MINUS = 501;
  int SHOW = 502;
  int SIMILAR = 503;
  int SIMPLE = 504;
  int SIZE = 505;
  int SKIP_ = 506;
  int SMALLINT = 507;
  int SOME = 508;
  int SOURCE = 509;
  int SPACE = 510;
  int SPECIFIC = 511;
  int SPECIFIC_NAME = 512;
  int SPECIFICTYPE = 513;
  int SQL = 514;
  int SQLEXCEPTION = 515;
  int SQLSTATE = 516;
  int SQLWARNING = 517;
  int SQL_BIGINT = 518;
  int SQL_BINARY = 519;
  int SQL_BIT = 520;
  int SQL_BLOB = 521;
  int SQL_BOOLEAN = 522;
  int SQL_CHAR = 523;
  int SQL_CLOB = 524;
  int SQL_DATE = 525;
  int SQL_DECIMAL = 526;
  int SQL_DOUBLE = 527;
  int SQL_FLOAT = 528;
  int SQL_INTEGER = 529;
  int SQL_INTERVAL_DAY = 530;
  int SQL_INTERVAL_DAY_TO_HOUR = 531;
  int SQL_INTERVAL_DAY_TO_MINUTE = 532;
  int SQL_INTERVAL_DAY_TO_SECOND = 533;
  int SQL_INTERVAL_HOUR = 534;
  int SQL_INTERVAL_HOUR_TO_MINUTE = 535;
  int SQL_INTERVAL_HOUR_TO_SECOND = 536;
  int SQL_INTERVAL_MINUTE = 537;
  int SQL_INTERVAL_MINUTE_TO_SECOND = 538;
  int SQL_INTERVAL_MONTH = 539;
  int SQL_INTERVAL_SECOND = 540;
  int SQL_INTERVAL_YEAR = 541;
  int SQL_INTERVAL_YEAR_TO_MONTH = 542;
  int SQL_LONGVARBINARY = 543;
  int SQL_LONGVARCHAR = 544;
  int SQL_LONGVARNCHAR = 545;
  int SQL_NCHAR = 546;
  int SQL_NCLOB = 547;
  int SQL_NUMERIC = 548;
  int SQL_NVARCHAR = 549;
  int SQL_REAL = 550;
  int SQL_SMALLINT = 551;
  int SQL_TIME = 552;
  int SQL_TIMESTAMP = 553;
  int SQL_TINYINT = 554;
  int SQL_TSI_DAY = 555;
  int SQL_TSI_FRAC_SECOND = 556;
  int SQL_TSI_HOUR = 557;
  int SQL_TSI_MICROSECOND = 558;
  int SQL_TSI_MINUTE = 559;
  int SQL_TSI_MONTH = 560;
  int SQL_TSI_QUARTER = 561;
  int SQL_TSI_SECOND = 562;
  int SQL_TSI_WEEK = 563;
  int SQL_TSI_YEAR = 564;
  int SQL_VARBINARY = 565;
  int SQL_VARCHAR = 566;
  int SQRT = 567;
  int START = 568;
  int STATE = 569;
  int STATEMENT = 570;
  int STATIC = 571;
  int STDDEV_POP = 572;
  int STDDEV_SAMP = 573;
  int STREAM = 574;
  int STRUCTURE = 575;
  int STYLE = 576;
  int SUBCLASS_ORIGIN = 577;
  int SUBMULTISET = 578;
  int SUBSET = 579;
  int SUBSTITUTE = 580;
  int SUBSTRING = 581;
  int SUBSTRING_REGEX = 582;
  int SUCCEEDS = 583;
  int SUM = 584;
  int SYMMETRIC = 585;
  int SYSTEM = 586;
  int SYSTEM_TIME = 587;
  int SYSTEM_USER = 588;
  int TABLE = 589;
  int TABLE_NAME = 590;
  int TABLESAMPLE = 591;
  int TEMPORARY = 592;
  int THEN = 593;
  int TIES = 594;
  int TIME = 595;
  int TIMESTAMP = 596;
  int TIMESTAMPADD = 597;
  int TIMESTAMPDIFF = 598;
  int TIMEZONE_HOUR = 599;
  int TIMEZONE_MINUTE = 600;
  int TINYINT = 601;
  int TO = 602;
  int TOP_LEVEL_COUNT = 603;
  int TRAILING = 604;
  int TRANSACTION = 605;
  int TRANSACTIONS_ACTIVE = 606;
  int TRANSACTIONS_COMMITTED = 607;
  int TRANSACTIONS_ROLLED_BACK = 608;
  int TRANSFORM = 609;
  int TRANSFORMS = 610;
  int TRANSLATE = 611;
  int TRANSLATE_REGEX = 612;
  int TRANSLATION = 613;
  int TREAT = 614;
  int TRIGGER = 615;
  int TRIGGER_CATALOG = 616;
  int TRIGGER_NAME = 617;
  int TRIGGER_SCHEMA = 618;
  int TRIM = 619;
  int TRIM_ARRAY = 620;
  int TRUE = 621;
  int TRUNCATE = 622;
  int TUMBLE = 623;
  int TYPE = 624;
  int UESCAPE = 625;
  int UNBOUNDED = 626;
  int UNCOMMITTED = 627;
  int UNCONDITIONAL = 628;
  int UNDER = 629;
  int UNION = 630;
  int UNIQUE = 631;
  int UNKNOWN = 632;
  int UNNAMED = 633;
  int UNNEST = 634;
  int UPDATE = 635;
  int UPPER = 636;
  int UPSERT = 637;
  int USAGE = 638;
  int USER = 639;
  int USER_DEFINED_TYPE_CATALOG = 640;
  int USER_DEFINED_TYPE_CODE = 641;
  int USER_DEFINED_TYPE_NAME = 642;
  int USER_DEFINED_TYPE_SCHEMA = 643;
  int USING = 644;
  int UTF8 = 645;
  int UTF16 = 646;
  int UTF32 = 647;
  int VALUE = 648;
  int VALUES = 649;
  int VALUE_OF = 650;
  int VAR_POP = 651;
  int VAR_SAMP = 652;
  int VARBINARY = 653;
  int VARCHAR = 654;
  int VARYING = 655;
  int VERSION = 656;
  int VERSIONING = 657;
  int VIEW = 658;
  int WEEK = 659;
  int WHEN = 660;
  int WHENEVER = 661;
  int WHERE = 662;
  int WIDTH_BUCKET = 663;
  int WINDOW = 664;
  int WITH = 665;
  int WITHIN = 666;
  int WITHOUT = 667;
  int WORK = 668;
  int WRAPPER = 669;
  int WRITE = 670;
  int XML = 671;
  int YEAR = 672;
  int YEARS = 673;
  int ZONE = 674;
  int BYTES = 675;
  int CATALOGS = 676;
  int CHANGELOG_MODE = 677;
  int COMMENT = 678;
  int DATABASES = 679;
  int ENFORCED = 680;
  int ESTIMATED_COST = 681;
  int EXTENDED = 682;
  int FUNCTIONS = 683;
  int IF = 684;
  int JSON_EXECUTION_PLAN = 685;
  int JAR = 686;
  int JARS = 687;
  int LOAD = 688;
  int METADATA = 689;
  int MODULES = 690;
  int OVERWRITE = 691;
  int OVERWRITING = 692;
  int PARTITIONED = 693;
  int PARTITIONS = 694;
  int PYTHON = 695;
  int RAW = 696;
  int REMOVE = 697;
  int RENAME = 698;
  int SCALA = 699;
  int STRING = 700;
  int TABLES = 701;
  int UNLOAD = 702;
  int USE = 703;
  int VIEWS = 704;
  int VIRTUAL = 705;
  int WATERMARK = 706;
  int WATERMARKS = 707;
  int TIMESTAMP_LTZ = 708;
  int UNSIGNED_INTEGER_LITERAL = 709;
  int APPROX_NUMERIC_LITERAL = 710;
  int DECIMAL_NUMERIC_LITERAL = 711;
  int EXPONENT = 712;
  int HEXDIGIT = 713;
  int WHITESPACE = 714;
  int BINARY_STRING_LITERAL = 715;
  int QUOTED_STRING = 716;
  int PREFIXED_STRING_LITERAL = 717;
  int UNICODE_STRING_LITERAL = 718;
  int CHARSETNAME = 719;
  int BIG_QUERY_DOUBLE_QUOTED_STRING = 720;
  int BIG_QUERY_QUOTED_STRING = 721;
  int UNICODE_QUOTED_ESCAPE_CHAR = 722;
  int LPAREN = 723;
  int RPAREN = 724;
  int LBRACE_D = 725;
  int LBRACE_T = 726;
  int LBRACE_TS = 727;
  int LBRACE_FN = 728;
  int LBRACE = 729;
  int RBRACE = 730;
  int LBRACKET = 731;
  int RBRACKET = 732;
  int SEMICOLON = 733;
  int DOT = 734;
  int COMMA = 735;
  int EQ = 736;
  int GT = 737;
  int LT = 738;
  int HOOK = 739;
  int COLON = 740;
  int LE = 741;
  int GE = 742;
  int NE = 743;
  int NE2 = 744;
  int PLUS = 745;
  int MINUS = 746;
  int STAR = 747;
  int SLASH = 748;
  int PERCENT_REMAINDER = 749;
  int CONCAT = 750;
  int NAMED_ARGUMENT_ASSIGNMENT = 751;
  int DOUBLE_PERIOD = 752;
  int QUOTE = 753;
  int DOUBLE_QUOTE = 754;
  int VERTICAL_BAR = 755;
  int CARET = 756;
  int DOLLAR = 757;
  int HINT_BEG = 763;
  int COMMENT_END = 764;
  int SINGLE_LINE_COMMENT = 767;
  int FORMAL_COMMENT = 768;
  int MULTI_LINE_COMMENT = 769;
  int BRACKET_QUOTED_IDENTIFIER = 771;
  int QUOTED_IDENTIFIER = 772;
  int BACK_QUOTED_IDENTIFIER = 773;
  int HYPHENATED_IDENTIFIER = 774;
  int IDENTIFIER = 775;
  int COLLATION_ID = 776;
  int UNICODE_QUOTED_IDENTIFIER = 777;
  int LETTER = 778;
  int DIGIT = 779;
  int BEL = 780;

  int DEFAULT = 0;
  int DQID = 1;
  int BTID = 2;
  int BQID = 3;
  int BQHID = 4;
  int IN_FORMAL_COMMENT = 5;
  int IN_MULTI_LINE_COMMENT = 6;

  String[] tokenImage = {
    "<EOF>",
    "\"A\"",
    "\"ABS\"",
    "\"ABSENT\"",
    "\"ABSOLUTE\"",
    "\"ACTION\"",
    "\"ADA\"",
    "\"ADD\"",
    "\"ADMIN\"",
    "\"AFTER\"",
    "\"ALL\"",
    "\"ALLOCATE\"",
    "\"ALLOW\"",
    "\"ALTER\"",
    "\"ALWAYS\"",
    "\"AND\"",
    "\"ANY\"",
    "\"APPLY\"",
    "\"ARE\"",
    "\"ARRAY\"",
    "\"ARRAY_MAX_CARDINALITY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"ASENSITIVE\"",
    "\"ASSERTION\"",
    "\"ASSIGNMENT\"",
    "\"ASYMMETRIC\"",
    "\"AT\"",
    "\"ATOMIC\"",
    "\"ATTRIBUTE\"",
    "\"ATTRIBUTES\"",
    "\"AUTHORIZATION\"",
    "\"AVG\"",
    "\"BEFORE\"",
    "\"BEGIN\"",
    "\"BEGIN_FRAME\"",
    "\"BEGIN_PARTITION\"",
    "\"BERNOULLI\"",
    "\"BETWEEN\"",
    "\"BIGINT\"",
    "\"BINARY\"",
    "\"BIT\"",
    "\"BLOB\"",
    "\"BOOLEAN\"",
    "\"BOTH\"",
    "\"BREADTH\"",
    "\"BY\"",
    "\"C\"",
    "\"CALL\"",
    "\"CALLED\"",
    "\"CARDINALITY\"",
    "\"CASCADE\"",
    "\"CASCADED\"",
    "\"CASE\"",
    "\"CAST\"",
    "\"CATALOG\"",
    "\"CATALOG_NAME\"",
    "\"CEIL\"",
    "\"CEILING\"",
    "\"CENTURY\"",
    "\"CHAIN\"",
    "\"CHAR\"",
    "\"CHAR_LENGTH\"",
    "\"CHARACTER\"",
    "\"CHARACTER_LENGTH\"",
    "\"CHARACTER_SET_CATALOG\"",
    "\"CHARACTER_SET_NAME\"",
    "\"CHARACTER_SET_SCHEMA\"",
    "\"CHARACTERISTICS\"",
    "\"CHARACTERS\"",
    "\"CHECK\"",
    "\"CLASSIFIER\"",
    "\"CLASS_ORIGIN\"",
    "\"CLOB\"",
    "\"CLOSE\"",
    "\"COALESCE\"",
    "\"COBOL\"",
    "\"COLLATE\"",
    "\"COLLATION\"",
    "\"COLLATION_CATALOG\"",
    "\"COLLATION_NAME\"",
    "\"COLLATION_SCHEMA\"",
    "\"COLLECT\"",
    "\"COLUMN\"",
    "\"COLUMN_NAME\"",
    "\"COMMAND_FUNCTION\"",
    "\"COMMAND_FUNCTION_CODE\"",
    "\"COMMIT\"",
    "\"COMMITTED\"",
    "\"CONDITION\"",
    "\"CONDITIONAL\"",
    "\"CONDITION_NUMBER\"",
    "\"CONNECT\"",
    "\"CONNECTION\"",
    "\"CONNECTION_NAME\"",
    "\"CONSTRAINT\"",
    "\"CONSTRAINT_CATALOG\"",
    "\"CONSTRAINT_NAME\"",
    "\"CONSTRAINT_SCHEMA\"",
    "\"CONSTRAINTS\"",
    "\"CONSTRUCTOR\"",
    "\"CONTAINS\"",
    "\"CONTINUE\"",
    "\"CONVERT\"",
    "\"CORR\"",
    "\"CORRESPONDING\"",
    "\"COUNT\"",
    "\"COVAR_POP\"",
    "\"COVAR_SAMP\"",
    "\"CREATE\"",
    "\"CROSS\"",
    "\"CUBE\"",
    "\"CUME_DIST\"",
    "\"CURRENT\"",
    "\"CURRENT_CATALOG\"",
    "\"CURRENT_DATE\"",
    "\"CURRENT_DEFAULT_TRANSFORM_GROUP\"",
    "\"CURRENT_PATH\"",
    "\"CURRENT_ROLE\"",
    "\"CURRENT_ROW\"",
    "\"CURRENT_SCHEMA\"",
    "\"CURRENT_TIME\"",
    "\"CURRENT_TIMESTAMP\"",
    "\"CURRENT_TRANSFORM_GROUP_FOR_TYPE\"",
    "\"CURRENT_USER\"",
    "\"CURSOR\"",
    "\"CURSOR_NAME\"",
    "\"CYCLE\"",
    "\"DATA\"",
    "\"DATABASE\"",
    "\"DATE\"",
    "\"DATETIME_INTERVAL_CODE\"",
    "\"DATETIME_INTERVAL_PRECISION\"",
    "\"DAY\"",
    "\"DAYS\"",
    "\"DEALLOCATE\"",
    "\"DEC\"",
    "\"DECADE\"",
    "\"DECIMAL\"",
    "\"DECLARE\"",
    "\"DEFAULT\"",
    "\"DEFAULTS\"",
    "\"DEFERRABLE\"",
    "\"DEFERRED\"",
    "\"DEFINE\"",
    "\"DEFINED\"",
    "\"DEFINER\"",
    "\"DEGREE\"",
    "\"DELETE\"",
    "\"DENSE_RANK\"",
    "\"DEPTH\"",
    "\"DEREF\"",
    "\"DERIVED\"",
    "\"DESC\"",
    "\"DESCRIBE\"",
    "\"DESCRIPTION\"",
    "\"DESCRIPTOR\"",
    "\"DETERMINISTIC\"",
    "\"DIAGNOSTICS\"",
    "\"DISALLOW\"",
    "\"DISCONNECT\"",
    "\"DISPATCH\"",
    "\"DISTINCT\"",
    "\"DOMAIN\"",
    "\"DOUBLE\"",
    "\"DOW\"",
    "\"DOY\"",
    "\"DROP\"",
    "\"DYNAMIC\"",
    "\"DYNAMIC_FUNCTION\"",
    "\"DYNAMIC_FUNCTION_CODE\"",
    "\"EACH\"",
    "\"ELEMENT\"",
    "\"ELSE\"",
    "\"EMPTY\"",
    "\"ENCODING\"",
    "\"END\"",
    "\"END-EXEC\"",
    "\"END_FRAME\"",
    "\"END_PARTITION\"",
    "\"EPOCH\"",
    "\"EQUALS\"",
    "\"ERROR\"",
    "\"ESCAPE\"",
    "\"EVERY\"",
    "\"EXCEPT\"",
    "\"EXCEPTION\"",
    "\"EXCLUDE\"",
    "\"EXCLUDING\"",
    "\"EXEC\"",
    "\"EXECUTE\"",
    "\"EXISTS\"",
    "\"EXP\"",
    "\"EXPLAIN\"",
    "\"EXTEND\"",
    "\"EXTERNAL\"",
    "\"EXTRACT\"",
    "\"FALSE\"",
    "\"FETCH\"",
    "\"FILTER\"",
    "\"FINAL\"",
    "\"FIRST\"",
    "\"FIRST_VALUE\"",
    "\"FLOAT\"",
    "\"FLOOR\"",
    "\"FOLLOWING\"",
    "\"FOR\"",
    "\"FORMAT\"",
    "\"FOREIGN\"",
    "\"FORTRAN\"",
    "\"FOUND\"",
    "\"FRAC_SECOND\"",
    "\"FRAME_ROW\"",
    "\"FREE\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"FUNCTION\"",
    "\"FUSION\"",
    "\"G\"",
    "\"GENERAL\"",
    "\"GENERATED\"",
    "\"GEOMETRY\"",
    "\"GET\"",
    "\"GLOBAL\"",
    "\"GO\"",
    "\"GOTO\"",
    "\"GRANT\"",
    "\"GRANTED\"",
    "\"GROUP\"",
    "\"GROUPING\"",
    "\"GROUPS\"",
    "\"HAVING\"",
    "\"HIERARCHY\"",
    "\"HOLD\"",
    "\"HOP\"",
    "\"HOUR\"",
    "\"HOURS\"",
    "\"IDENTITY\"",
    "\"IGNORE\"",
    "\"IMMEDIATE\"",
    "\"IMMEDIATELY\"",
    "\"IMPLEMENTATION\"",
    "\"IMPORT\"",
    "\"IN\"",
    "\"INCLUDING\"",
    "\"INCREMENT\"",
    "\"INDICATOR\"",
    "\"INITIAL\"",
    "\"INITIALLY\"",
    "\"INNER\"",
    "\"INOUT\"",
    "\"INPUT\"",
    "\"INSENSITIVE\"",
    "\"INSERT\"",
    "\"INSTANCE\"",
    "\"INSTANTIABLE\"",
    "\"INT\"",
    "\"INTEGER\"",
    "\"INTERSECT\"",
    "\"INTERSECTION\"",
    "\"INTERVAL\"",
    "\"INTO\"",
    "\"INVOKER\"",
    "\"IS\"",
    "\"ISODOW\"",
    "\"ISOYEAR\"",
    "\"ISOLATION\"",
    "\"JAVA\"",
    "\"JOIN\"",
    "\"JSON\"",
    "\"JSON_ARRAY\"",
    "\"JSON_ARRAYAGG\"",
    "\"JSON_EXISTS\"",
    "\"JSON_OBJECT\"",
    "\"JSON_OBJECTAGG\"",
    "\"JSON_QUERY\"",
    "\"JSON_VALUE\"",
    "\"K\"",
    "\"KEY\"",
    "\"KEY_MEMBER\"",
    "\"KEY_TYPE\"",
    "\"LABEL\"",
    "\"LAG\"",
    "\"LANGUAGE\"",
    "\"LARGE\"",
    "\"LAST\"",
    "\"LAST_VALUE\"",
    "\"LATERAL\"",
    "\"LEAD\"",
    "\"LEADING\"",
    "\"LEFT\"",
    "\"LENGTH\"",
    "\"LEVEL\"",
    "\"LIBRARY\"",
    "\"LIKE\"",
    "\"LIKE_REGEX\"",
    "\"LIMIT\"",
    "\"LN\"",
    "\"LOCAL\"",
    "\"LOCALTIME\"",
    "\"LOCALTIMESTAMP\"",
    "\"LOCATOR\"",
    "\"LOWER\"",
    "\"M\"",
    "\"MAP\"",
    "\"MATCH\"",
    "\"MATCHED\"",
    "\"MATCHES\"",
    "\"MATCH_NUMBER\"",
    "\"MATCH_RECOGNIZE\"",
    "\"MAX\"",
    "\"MAXVALUE\"",
    "\"MEASURES\"",
    "\"MEMBER\"",
    "\"MERGE\"",
    "\"MESSAGE_LENGTH\"",
    "\"MESSAGE_OCTET_LENGTH\"",
    "\"MESSAGE_TEXT\"",
    "\"METHOD\"",
    "\"MICROSECOND\"",
    "\"MILLISECOND\"",
    "\"MILLENNIUM\"",
    "\"MIN\"",
    "\"MINUTE\"",
    "\"MINUTES\"",
    "\"MINVALUE\"",
    "\"MOD\"",
    "\"MODIFIES\"",
    "\"MODULE\"",
    "\"MONTH\"",
    "\"MONTHS\"",
    "\"MORE\"",
    "\"MULTISET\"",
    "\"MUMPS\"",
    "\"NAME\"",
    "\"NAMES\"",
    "\"NANOSECOND\"",
    "\"NATIONAL\"",
    "\"NATURAL\"",
    "\"NCHAR\"",
    "\"NCLOB\"",
    "\"NESTING\"",
    "\"NEW\"",
    "\"NEXT\"",
    "\"NO\"",
    "\"NONE\"",
    "\"NORMALIZE\"",
    "\"NORMALIZED\"",
    "\"NOT\"",
    "\"NTH_VALUE\"",
    "\"NTILE\"",
    "\"NULL\"",
    "\"NULLABLE\"",
    "\"NULLIF\"",
    "\"NULLS\"",
    "\"NUMBER\"",
    "\"NUMERIC\"",
    "\"OBJECT\"",
    "\"OCCURRENCES_REGEX\"",
    "\"OCTET_LENGTH\"",
    "\"OCTETS\"",
    "\"OF\"",
    "\"OFFSET\"",
    "\"OLD\"",
    "\"OMIT\"",
    "\"ON\"",
    "\"ONE\"",
    "\"ONLY\"",
    "\"OPEN\"",
    "\"OPTION\"",
    "\"OPTIONS\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"ORDERING\"",
    "\"ORDINALITY\"",
    "\"OTHERS\"",
    "\"OUT\"",
    "\"OUTER\"",
    "\"OUTPUT\"",
    "\"OVER\"",
    "\"OVERLAPS\"",
    "\"OVERLAY\"",
    "\"OVERRIDING\"",
    "\"PAD\"",
    "\"PARAMETER\"",
    "\"PARAMETER_MODE\"",
    "\"PARAMETER_NAME\"",
    "\"PARAMETER_ORDINAL_POSITION\"",
    "\"PARAMETER_SPECIFIC_CATALOG\"",
    "\"PARAMETER_SPECIFIC_NAME\"",
    "\"PARAMETER_SPECIFIC_SCHEMA\"",
    "\"PARTIAL\"",
    "\"PARTITION\"",
    "\"PASCAL\"",
    "\"PASSING\"",
    "\"PASSTHROUGH\"",
    "\"PAST\"",
    "\"PATH\"",
    "\"PATTERN\"",
    "\"PER\"",
    "\"PERCENT\"",
    "\"PERCENTILE_CONT\"",
    "\"PERCENTILE_DISC\"",
    "\"PERCENT_RANK\"",
    "\"PERIOD\"",
    "\"PERMUTE\"",
    "\"PIVOT\"",
    "\"PLACING\"",
    "\"PLAN\"",
    "\"PLI\"",
    "\"PORTION\"",
    "\"POSITION\"",
    "\"POSITION_REGEX\"",
    "\"POWER\"",
    "\"PRECEDES\"",
    "\"PRECEDING\"",
    "\"PRECISION\"",
    "\"PREPARE\"",
    "\"PRESERVE\"",
    "\"PREV\"",
    "\"PRIMARY\"",
    "\"PRIOR\"",
    "\"PRIVILEGES\"",
    "\"PROCEDURE\"",
    "\"PUBLIC\"",
    "\"QUARTER\"",
    "\"RANGE\"",
    "\"RANK\"",
    "\"READ\"",
    "\"READS\"",
    "\"REAL\"",
    "\"RECURSIVE\"",
    "\"REF\"",
    "\"REFERENCES\"",
    "\"REFERENCING\"",
    "\"REGR_AVGX\"",
    "\"REGR_AVGY\"",
    "\"REGR_COUNT\"",
    "\"REGR_INTERCEPT\"",
    "\"REGR_R2\"",
    "\"REGR_SLOPE\"",
    "\"REGR_SXX\"",
    "\"REGR_SXY\"",
    "\"REGR_SYY\"",
    "\"RELATIVE\"",
    "\"RELEASE\"",
    "\"REPEATABLE\"",
    "\"REPLACE\"",
    "\"RESET\"",
    "\"RESPECT\"",
    "\"RESTART\"",
    "\"RESTRICT\"",
    "\"RESULT\"",
    "\"RETURN\"",
    "\"RETURNED_CARDINALITY\"",
    "\"RETURNED_LENGTH\"",
    "\"RETURNED_OCTET_LENGTH\"",
    "\"RETURNED_SQLSTATE\"",
    "\"RETURNING\"",
    "\"RETURNS\"",
    "\"REVOKE\"",
    "\"RIGHT\"",
    "\"ROLE\"",
    "\"ROLLBACK\"",
    "\"ROLLUP\"",
    "\"ROUTINE\"",
    "\"ROUTINE_CATALOG\"",
    "\"ROUTINE_NAME\"",
    "\"ROUTINE_SCHEMA\"",
    "\"ROW\"",
    "\"ROW_COUNT\"",
    "\"ROW_NUMBER\"",
    "\"ROWS\"",
    "\"RUNNING\"",
    "\"SAVEPOINT\"",
    "\"SCALAR\"",
    "\"SCALE\"",
    "\"SCHEMA\"",
    "\"SCHEMA_NAME\"",
    "\"SCOPE\"",
    "\"SCOPE_CATALOGS\"",
    "\"SCOPE_NAME\"",
    "\"SCOPE_SCHEMA\"",
    "\"SCROLL\"",
    "\"SEARCH\"",
    "\"SECOND\"",
    "\"SECONDS\"",
    "\"SECTION\"",
    "\"SECURITY\"",
    "\"SEEK\"",
    "\"SELECT\"",
    "\"SELF\"",
    "\"SENSITIVE\"",
    "\"SEQUENCE\"",
    "\"SERIALIZABLE\"",
    "\"SERVER\"",
    "\"SERVER_NAME\"",
    "\"SESSION\"",
    "\"SESSION_USER\"",
    "\"SET\"",
    "\"SETS\"",
    "\"MINUS\"",
    "\"SHOW\"",
    "\"SIMILAR\"",
    "\"SIMPLE\"",
    "\"SIZE\"",
    "\"SKIP\"",
    "\"SMALLINT\"",
    "\"SOME\"",
    "\"SOURCE\"",
    "\"SPACE\"",
    "\"SPECIFIC\"",
    "\"SPECIFIC_NAME\"",
    "\"SPECIFICTYPE\"",
    "\"SQL\"",
    "\"SQLEXCEPTION\"",
    "\"SQLSTATE\"",
    "\"SQLWARNING\"",
    "\"SQL_BIGINT\"",
    "\"SQL_BINARY\"",
    "\"SQL_BIT\"",
    "\"SQL_BLOB\"",
    "\"SQL_BOOLEAN\"",
    "\"SQL_CHAR\"",
    "\"SQL_CLOB\"",
    "\"SQL_DATE\"",
    "\"SQL_DECIMAL\"",
    "\"SQL_DOUBLE\"",
    "\"SQL_FLOAT\"",
    "\"SQL_INTEGER\"",
    "\"SQL_INTERVAL_DAY\"",
    "\"SQL_INTERVAL_DAY_TO_HOUR\"",
    "\"SQL_INTERVAL_DAY_TO_MINUTE\"",
    "\"SQL_INTERVAL_DAY_TO_SECOND\"",
    "\"SQL_INTERVAL_HOUR\"",
    "\"SQL_INTERVAL_HOUR_TO_MINUTE\"",
    "\"SQL_INTERVAL_HOUR_TO_SECOND\"",
    "\"SQL_INTERVAL_MINUTE\"",
    "\"SQL_INTERVAL_MINUTE_TO_SECOND\"",
    "\"SQL_INTERVAL_MONTH\"",
    "\"SQL_INTERVAL_SECOND\"",
    "\"SQL_INTERVAL_YEAR\"",
    "\"SQL_INTERVAL_YEAR_TO_MONTH\"",
    "\"SQL_LONGVARBINARY\"",
    "\"SQL_LONGVARCHAR\"",
    "\"SQL_LONGVARNCHAR\"",
    "\"SQL_NCHAR\"",
    "\"SQL_NCLOB\"",
    "\"SQL_NUMERIC\"",
    "\"SQL_NVARCHAR\"",
    "\"SQL_REAL\"",
    "\"SQL_SMALLINT\"",
    "\"SQL_TIME\"",
    "\"SQL_TIMESTAMP\"",
    "\"SQL_TINYINT\"",
    "\"SQL_TSI_DAY\"",
    "\"SQL_TSI_FRAC_SECOND\"",
    "\"SQL_TSI_HOUR\"",
    "\"SQL_TSI_MICROSECOND\"",
    "\"SQL_TSI_MINUTE\"",
    "\"SQL_TSI_MONTH\"",
    "\"SQL_TSI_QUARTER\"",
    "\"SQL_TSI_SECOND\"",
    "\"SQL_TSI_WEEK\"",
    "\"SQL_TSI_YEAR\"",
    "\"SQL_VARBINARY\"",
    "\"SQL_VARCHAR\"",
    "\"SQRT\"",
    "\"START\"",
    "\"STATE\"",
    "\"STATEMENT\"",
    "\"STATIC\"",
    "\"STDDEV_POP\"",
    "\"STDDEV_SAMP\"",
    "\"STREAM\"",
    "\"STRUCTURE\"",
    "\"STYLE\"",
    "\"SUBCLASS_ORIGIN\"",
    "\"SUBMULTISET\"",
    "\"SUBSET\"",
    "\"SUBSTITUTE\"",
    "\"SUBSTRING\"",
    "\"SUBSTRING_REGEX\"",
    "\"SUCCEEDS\"",
    "\"SUM\"",
    "\"SYMMETRIC\"",
    "\"SYSTEM\"",
    "\"SYSTEM_TIME\"",
    "\"SYSTEM_USER\"",
    "\"TABLE\"",
    "\"TABLE_NAME\"",
    "\"TABLESAMPLE\"",
    "\"TEMPORARY\"",
    "\"THEN\"",
    "\"TIES\"",
    "\"TIME\"",
    "\"TIMESTAMP\"",
    "\"TIMESTAMPADD\"",
    "\"TIMESTAMPDIFF\"",
    "\"TIMEZONE_HOUR\"",
    "\"TIMEZONE_MINUTE\"",
    "\"TINYINT\"",
    "\"TO\"",
    "\"TOP_LEVEL_COUNT\"",
    "\"TRAILING\"",
    "\"TRANSACTION\"",
    "\"TRANSACTIONS_ACTIVE\"",
    "\"TRANSACTIONS_COMMITTED\"",
    "\"TRANSACTIONS_ROLLED_BACK\"",
    "\"TRANSFORM\"",
    "\"TRANSFORMS\"",
    "\"TRANSLATE\"",
    "\"TRANSLATE_REGEX\"",
    "\"TRANSLATION\"",
    "\"TREAT\"",
    "\"TRIGGER\"",
    "\"TRIGGER_CATALOG\"",
    "\"TRIGGER_NAME\"",
    "\"TRIGGER_SCHEMA\"",
    "\"TRIM\"",
    "\"TRIM_ARRAY\"",
    "\"TRUE\"",
    "\"TRUNCATE\"",
    "\"TUMBLE\"",
    "\"TYPE\"",
    "\"UESCAPE\"",
    "\"UNBOUNDED\"",
    "\"UNCOMMITTED\"",
    "\"UNCONDITIONAL\"",
    "\"UNDER\"",
    "\"UNION\"",
    "\"UNIQUE\"",
    "\"UNKNOWN\"",
    "\"UNNAMED\"",
    "\"UNNEST\"",
    "\"UPDATE\"",
    "\"UPPER\"",
    "\"UPSERT\"",
    "\"USAGE\"",
    "\"USER\"",
    "\"USER_DEFINED_TYPE_CATALOG\"",
    "\"USER_DEFINED_TYPE_CODE\"",
    "\"USER_DEFINED_TYPE_NAME\"",
    "\"USER_DEFINED_TYPE_SCHEMA\"",
    "\"USING\"",
    "\"UTF8\"",
    "\"UTF16\"",
    "\"UTF32\"",
    "\"VALUE\"",
    "\"VALUES\"",
    "\"VALUE_OF\"",
    "\"VAR_POP\"",
    "\"VAR_SAMP\"",
    "\"VARBINARY\"",
    "\"VARCHAR\"",
    "\"VARYING\"",
    "\"VERSION\"",
    "\"VERSIONING\"",
    "\"VIEW\"",
    "\"WEEK\"",
    "\"WHEN\"",
    "\"WHENEVER\"",
    "\"WHERE\"",
    "\"WIDTH_BUCKET\"",
    "\"WINDOW\"",
    "\"WITH\"",
    "\"WITHIN\"",
    "\"WITHOUT\"",
    "\"WORK\"",
    "\"WRAPPER\"",
    "\"WRITE\"",
    "\"XML\"",
    "\"YEAR\"",
    "\"YEARS\"",
    "\"ZONE\"",
    "\"BYTES\"",
    "\"CATALOGS\"",
    "\"CHANGELOG_MODE\"",
    "\"COMMENT\"",
    "\"DATABASES\"",
    "\"ENFORCED\"",
    "\"ESTIMATED_COST\"",
    "\"EXTENDED\"",
    "\"FUNCTIONS\"",
    "\"IF\"",
    "\"JSON_EXECUTION_PLAN\"",
    "\"JAR\"",
    "\"JARS\"",
    "\"LOAD\"",
    "\"METADATA\"",
    "\"MODULES\"",
    "\"OVERWRITE\"",
    "\"OVERWRITING\"",
    "\"PARTITIONED\"",
    "\"PARTITIONS\"",
    "\"PYTHON\"",
    "\"RAW\"",
    "\"REMOVE\"",
    "\"RENAME\"",
    "\"SCALA\"",
    "\"STRING\"",
    "\"TABLES\"",
    "\"UNLOAD\"",
    "\"USE\"",
    "\"VIEWS\"",
    "\"VIRTUAL\"",
    "\"WATERMARK\"",
    "\"WATERMARKS\"",
    "\"TIMESTAMP_LTZ\"",
    "<UNSIGNED_INTEGER_LITERAL>",
    "<APPROX_NUMERIC_LITERAL>",
    "<DECIMAL_NUMERIC_LITERAL>",
    "<EXPONENT>",
    "<HEXDIGIT>",
    "<WHITESPACE>",
    "<BINARY_STRING_LITERAL>",
    "<QUOTED_STRING>",
    "<PREFIXED_STRING_LITERAL>",
    "<UNICODE_STRING_LITERAL>",
    "<CHARSETNAME>",
    "<BIG_QUERY_DOUBLE_QUOTED_STRING>",
    "<BIG_QUERY_QUOTED_STRING>",
    "<UNICODE_QUOTED_ESCAPE_CHAR>",
    "\"(\"",
    "\")\"",
    "<LBRACE_D>",
    "<LBRACE_T>",
    "<LBRACE_TS>",
    "<LBRACE_FN>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\".\"",
    "\",\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"?\"",
    "\":\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"||\"",
    "\"=>\"",
    "\"..\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"|\"",
    "\"^\"",
    "\"$\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*+\"",
    "\"*/\"",
    "<token of kind 765>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<token of kind 770>",
    "<BRACKET_QUOTED_IDENTIFIER>",
    "<QUOTED_IDENTIFIER>",
    "<BACK_QUOTED_IDENTIFIER>",
    "<HYPHENATED_IDENTIFIER>",
    "<IDENTIFIER>",
    "<COLLATION_ID>",
    "<UNICODE_QUOTED_IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<BEL>",
  };

}
